In [1]:
import numpy as np
n=int(input("enter the size of identity matrix: "))
a=np.identity(n)
print(a)

enter the size of identity matrix: 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
